<!doctype html>
<html>
<head>
<?php $this->load->view('common/head'); ?>
<link rel="stylesheet" type="text/css" href="<?php echo CSS_URL; ?>bda.css">
</head>
<body>
<div id="header">
	<h1 class="display-none">Book Doctor Appointment - Privacy Policy</h1>
	<?php $this->load->view('common/header');?>
</div>

<div id="content"><!--content Start-->

<div class="container cf"><!--container cf Start-->
<div id="Privacy_Policy_April">


                	<h1 >Privacy Policy</h1>

                    <span>1 Who is BDA (Bookdrappointment.com)?</span>

                    <p>1.	Pharma and Medical Concepts Private Limited is the author and publisher of the software BDA for doctors (BDA DOC), and all variants, editions, add-ons, and ancillary products or services of BDA for Doctors(BDA DOC) (including all files and images contained in or generated by the software, and accompanying data, together the <strong>“Software”</strong>). BDA also operates the internet resource www.bookdrappointment.com (<strong>“Website”</strong>) on world wide web which is used to access BDA Software. BDA Software is used at healthcare practices (<strong>“Practices”</strong>) by healthcare providers (<strong>“Practitioners”</strong>, which term shall also include designated associates of the healthcare providers who work in the same Practice), and clients of the healthcare providers (<strong>“Patients”</strong>, which term shall also include members of public who search for doctors on the Website) to find, manage and organise information including but not limited to personal or non-personal information, practice information, appointments, prescriptions, medical records, billing, inventory and accounting details. All users of the BDA Software - the Practitioners, Patients, and the visitors of Website are together termed as <strong>“Users”</strong>.</p>

                    

                    <span>2 How does BDA protect Customer Data?</span>

                    <p>2.1 BDA provides its services in SaaS (Software as a Service) model, and will host data and information. BDA will not review, share, distribute, or reference any such User data except as provided in the terms of use, or as may be required by law. Individual records of User data may be viewed or accessed only for the purpose of resolving a problem, support issues, or suspected violation of the terms of use, or as may be required by law. We would take all reasonable precautions for maintaining confidentiality of data.</p>

                    

                    <span>3 How can I contact BDA?</span>

                    <p>3.1 BDA can be reached, for all questions and directions related to this privacy 

policy, by:

Sending a letter marked to the attention to <strong>“Sachin Mishra”</strong>, Pharma and Medical Concepts Pvt Ltd, Sb 48, 2nd floor, Highland corporate Center, High Street Mall, Kapurbawdi, Thane (West) -400607<br />

<strong>Or</strong><br />

Sending an email to <a href="mailto:privacy@bda.com">privacy@BDA.com</a>.<br /><br />

</p>
 			<span>4. Why this privacy policy?</span>
			<p>4.1 This privacy policy is published in compliance of:</p>	
            <p>i. Section 43A of the Information Technology Act, 2000;</p>
            <p>ii. Regulation 4 of the Information Technology (Reasonable Security 

Practices and Procedures and Sensitive Personal Information) Rules, 

2011 (the “SPI Rules”); and</p>
<p>iii.Regulation 3(1) of the Information Technology (Intermediaries 

Guidelines) Rules, 2011.</p><br />

<p>4.2 This privacy policy states the following:</p>

<p>i. The type of information collected from the visitors of the Website and 

the End users, including sensitive personal data or information;</p>

<p>ii. The purpose, means and modes of usage of such information; and</p>

<p>iii. How and to whom BDA will disclose such information.</p>

<span>5. What is personal information?</span>
<p>5.1 “Personal information” is defined under the SPI Rules to mean any information 

that relates to a natural person, which, either directly or indirectly, in combination 

with other information available or likely to be available with a body corporate, is 

capable of identifying such person.</p>
<br/>
<p>i. passwords;</p>
<p>ii. financial information such as bank accounts, credit and debit card 

details or other payment instrument details;</p>
<p>iii. physical, physiological and mental health condition;</p>
<p>iv. sexual orientation;</p>
<p>v. medical records and history;</p>
<p>vi. biometric information;</p>
<p>vii.information received by body corporate under lawful contract or 

otherwise;</p>
<p>viii. visitor details as provided at the time of registration or thereafter; and</p>
<p>ix. call data records.</p><br/>
<p>5.3 Information that is freely available in the public domain or accessible under the 

Right to Information Act, 2005 or any other law will not be regarded as sensitive 

personal data or information.</p>

<span>Privacy Statements</span>
<span>5. All Users Note:</span>
<p>6.1 This section applies to all Users (“Users”).</p><br/>
<p>6.2 Accordingly, a condition of each User’s use of and access to the Website and to 

the Software provided by BDA to Users (together with the Website, the “Services”) 

is their acceptance of the terms of use located at Part B below, which also involves 

acceptance of the terms of this privacy policy. Any User that does not agree with 

any provisions of the same is required to leave the Website immediately.</p><br/>
<p>6.3 All the information provided to BDA by a User, including sensitive personal 

information, is voluntary. User has the right to withdraw his/her/its consent at any 

time, in accordance with the terms of this privacy policy and the terms of use, but 

please note that withdrawal of consent will not be retroactive.<strong>Always use caution

when giving out any personally identifiable information about yourself 

or your family members in use of any Services. BDA does not control 

or endorse the content, messages or information found in any Services 

and, therefore, BDA specifically disclaims any liability with regard to the 

Services and any actions resulting from your participation in any Services, 

and you agree that you waive any claims against BDA relating to same, 

and to the extent such waiver may be ineffective, you agree to release any 

claims against BDA relating to same.</strong></p><br/>

<p>6.4 User can access, modify, correct and eliminate the data about him/her/it

which has been collected pursuant to his/her/its decision to become a User. If User 

updates any of his/her/its information, BDA may keep a copy of the information 

which User originally provided to BDA in its archives for uses documented herein. 

BDA takes User’s rights seriously and encourages User to use them if User 

deems this to be appropriate. User may exercise these rights by emailing BDA at 

privacy@BDA.com.</p><br/>
<p>6.5 BDA may require the User to pay with a credit card, wire transfer, debit card 

or cheque. BDA will collect such User’s credit card number and/or other financial 

institution information such as bank account numbers and will use that information 

for the billing and payment processes, including but not limited to the use and 

disclosure of such credit card number and information to third parties as necessary 

to complete such billing operation. Verification of credit information, however, is 

accomplished solely by the User through the authentication process. User’s credit-
card/debit card details are transacted upon secure sites of approved payment 

gateways which are digitally under encryption, thereby providing the highest 

possible degree of care as per current technology. User is advised, however, that 

internet technology is not 100% safe and User should exercise discretion on using 

the same.</p><br/>
<p>6.6 Due to the communications standards on the Internet, when a User visits the 

Website, BDA automatically receive the URL of the site from which such User came 

and the site to which such User is going when he/she/it leaves. BDA also receives 

the Internet Protocol (IP) address of each User’s computer (or the proxy server 

a User used to access the World Wide Web), User’s computer operating system 

and type of web browser the User is using, email patterns, as well as the name of 

User’s ISP. This information is used to analyze overall trends to help BDA improve 

its Service. The linkage between User’s IP address and User’s personally identifiable 

information is not shared with third parties without such User’s permission or 

except when required by law. Notwithstanding the above, BDA may share some of 

the aggregate findings (not the specific data) with advertisers, sponsors, investors, 

strategic partners, and others in order to help grow its business.</p><br/>

<p>6.7 The Website uses temporary cookies to store certain data (that is not sensitive 

personal data or information) that is used by BDA and its service providers for the 

technical administration of the Website, research and development, and for User 

administration. In the course of serving advertisements or optimizing services to its 

Users, BDA may allow authorized third parties to place or recognize a unique cookie 

on the User’s browser. BDA does not store personally identifiable information in the 

cookies.</p><br/>
<p>6.8 A User may have limited access to the Website and make appointments with 

the doctors without creating an account on the Website. Unregistered Users can 

make appointments with the doctors by providing their name and phone number. 

In order to have access to all the features and benefits on our Website, a User must 

first create an account on our Website. To create an account a User is required 

to provide the following information, which such User recognizes and expressly 

acknowledges is personal information allowing others, including BDA, to identify the 

User: name, User ID, email address, country, ZIP/postal code, age, phone number, 

password chosen by the User and valid financial account information. Other 

information requested on the registration page, including the ability to receive 

promotional offers from BDA, is optional. BDA may, in future, include other optional 

requests for information from the User to help BDA to customize the Website to 

deliver personalized information to the User. Without User’s consent, BDA will not 

share, rent or sell any personal information with third parties in any way other than 

what is disclosed in this privacy policy.</p><br/>
<p>6.9 BDA allows other companies, to serve advertisements to the Users. These 

companies include but not limited to third party ad servers, ad agencies, ad 

technology vendors and research firms. BDA may display advertisements to Users 

that fit a certain general profile criteria (<strong>“Targets”</strong>). BDA does NOT use personally 

identifiable information to identify Targets for advertising on its Services.</p><br/>
<p>6.10 This privacy policy applies to Services that are owned and operated by BDA. 

BDA does not exercise control over the sites displayed as search results or links 

from within its Services. These other sites may place their own cookies or other 

files on the Users’ computer, collect data or solicit personal information from the 

Users, for which BDA is not responsible or liable. Accordingly, BDA does not make 

any representations concerning the privacy practices or policies of such third parties 

or terms of use of such websites, nor does BDA guarantee the accuracy, integrity, 

or quality of the information, data, text, software, sound, photographs, graphics, 

videos, messages or other materials available on such websites. The inclusion or 

exclusion does not imply any endorsement by BDA of the website, the website's 

provider, or the information on the website. BDA encourages the User to read the 

privacy policies of that website.</p><br/>
<p>6.11 The Website may enable User to communicate with other Users or to post 

information to be accessed by others, whereupon other Users may collect such 

data. Such Users, including any moderators or administrators, are not authorized 

BDA representatives or agents, and their opinions or statements do not necessarily 

reflect those of BDA, and they are not authorized to bind BDA to any contract. <strong>BDA 

hereby expressly disclaims any liability for any reliance or misuse of such 

information that is made available by Users or visitors in such a manner.</strong></p><br/>
<p>6.12 BDA does not collect information about the visitors of the Website from other 

sources, such as public records or bodies, or private organisations, save and except 

for the purposes of registration of the Users (the collection, storage and disclosure 

of which each End User must agree to under the terms of use in order for BDA to 

effectively render the Services).</p><br/>
<p>6.13 BDA does not knowingly collect personal data from children.</p><br/>
<p>6.14 BDA has implemented Indian legal industry standard security policies, rules 

and technical measures to protect the personal data that it has under its control 

from unauthorised access, improper use or disclosure, unauthorised modification 

and unlawful destruction or accidental loss.</p><br/>
<p>6.15 BDA will not disclose any personal information or data to governmental 

institutions or authorities unless such disclosure is requisitioned under any Indian 

law or judicial decree or when BDA, in its sole discretion, deems it necessary in 

order to protect its rights or the rights of others, to prevent harm to persons or 

property, to fight fraud and credit risk, or to enforce or apply our terms of use.</p><br/>
<p>6.16 BDA addresses any discrepancies and grievances of all Users with respect 

to processing of information in a time bound manner. For this purpose, BDA has 

hired professional who will redress the grievances of the Users expeditiously within 

a maximum of one month from the date of receipt of grievance, and who can be 

reached by:</p><br/>

<p>Sending a letter marked to the attention of “Sachin Mishra” to Pharma and Medical 

Concepts Pvt Ltd, Sb 48, 2nd floor, Highland corporate Center, High Street Mall, 

Kapurbawdi, Thane (West) -400607</p><br/>

<p>i. Sending an email to support@bookdrappointment.com.</p><br/>
<span>7. Practitioners Note:</span>
<p>7.1 This section is applicable to Practitioners (<strong>“Practitioners”</strong>)</p><br/>
<p>7.2 As part of the registration/application creation and submission process that 

is available to Practitioners on Website, certain information, including sensitive 

personal data or information is collected from the Practitioners.</p><br/>
<p>7.3 All the statements in this privacy policy apply to all Practitioners, and all 

Practitioners are therefore required to read and understand the privacy statements 

set out herein prior to submitting any sensitive personal data or information to 

BDA, failing which they are required to leave this Website immediately.</p><br/>
<p>7.4 Practitioners personally identifiable information they choose to provide on 

the Website is used to help the Practitioners describe / identify themselves. This 

information is exclusively owned by BDA. BDA may use such information for 

commercial purposes and in an aggregated or non-personally identifiable form for 

research, statistical analysis and business intelligence purposes, and may sell or 

otherwise transfer such research, statistical or intelligence data in an aggregated or 

non-personally identifiable form to third parties and affiliates.</p><br/>
<p>7.5 BDA automatically lists Practitioners’ information on its Website for

every ‘Doctor’ added to a Practice using its Software. The Practitioner information 

listed on Website is displayed when Patients search for doctors on Website, and the 

Practitioner information listed on Website is used by Patients to request for doctor 

appointments. BDA, on its own, does not list any Personally Sensitive Information 

of such Practitioners.</p><br/>
<p>7.6 BDA also creates Practitioners’ information for Practitioners that have not 

signed up or registered for BDA Services. Such Practitioners are manually verified 

over phone or in person by BDA or its associates, and BDA makes every effort to 

capture accurate information for such Practitioners. However, BDA does not hold 

any liability for any incorrect or incomplete information appearing on Website for 

such Practitioners.</p><br/>
<span>8. Patients Note:</span>
<p>8.1 This section is applicable to Patients (<strong>“Patients”</strong>)</p><br/>
<p>8.2 As part of the registration/application creation and submission process that

is available to Patients on this website, certain information, including sensitive 

personal data or information is collected from the Users.</p><br/>
<p>8.3 All the statements in this privacy policy apply to all Patients, and all Patients are 

therefore required to read and understand the privacy statements set out herein 

prior to submitting any sensitive personal data or information to BDA, failing which 

they are required to leave this Website immediately.</p><br/>
<p>8.4 <strong>If you have inadvertently submitted any such information to BDA prior 

to reading the privacy statements set out herein,</strong> and you do not agree 

with the manner in which such information is collected, stored or used, then you 

may access, modify and delete all information stored about you by BDA by using 

options provided on the Website. In addition, any Patients can ask BDA, by sending 

an email to privacy@bookdrappointment.com whether BDA is keeping personal 

data about him/her, and every Patient is also entitled to require BDA to delete 

and destroy all such information relating to him/her (but not other Users) in its 

possession.</p><br/>
<p>8.5 Patients’ personally identifiable information they choose to provide on the 

Website is used to help the Patients describe/identify themselves. Other information 

that does not personally identify the Patients as an individual, is collected by 

BDA from Patients (such as, patterns of utilization described above) and is 

exclusively owned by BDA. BDA may also use such information in an aggregated 

or non-personally identifiable form for research, statistical analysis and business 

intelligence purposes, and may sell or otherwise transfer such research, statistical 

or intelligence data in an aggregated or non-personally identifiable form to third 

parties and affiliates. If BDA wishes to use any Patients’ personal data for a new 

purpose, it will seek Patients’ permission before doing so.</p><br/>
<p>8.6 BDA will communicate with the Patients through email, phone and notices 

posted on the Website or through other means available through the service, 

including text and other forms of messaging based on Patients contact preferences. 

The Patients can change their e-mail and contact preferences at any time by 

logging into their "Account" at www.bookdrappointment.com and changing the 

account settings.</p><br/>
<p>8.7 At times, BDA conducts a User survey to collect information about Patients' 

preferences. These surveys are optional and if Patients choose to respond, their 

responses will be kept anonymous. Similarly, BDA may offer contests to qualifying 

Patients in which we ask for contact and demographic information such as name, 


email address and mailing address. None of this information is shared with third 

parties, except in summary form, if at all. The demographic information that 

BDA collects in the registration process and through surveys is used to help BDA 

improve its Services to meet the needs and preferences of Patients. This may 

include targeting advertising to Patients about our Services. Information we gather 

through a contest may also be disclosed to third parties, as necessary, for prize 

fulfillment and other aspects of any contest or similar offering.</p><br/>
<p>8.9 All BDA employees and data processors, who have access to, and are 

associated with the processing of sensitive personal data or information, are 

obliged to respect the confidentiality of every Patients’ sensitive personal data and 

information.</p><br/>
<p>8.10 BDA may also disclose or transfer Patients’ personal and other information 

a User provides, to another third party as part of reorganization or a sale of the 

assets of a BDA corporation division or company. Any third party to which BDA 

transfers or sells its assets will have the right to continue to use the personal and 

other information that Patients provide to us.</p><br/>
<p>8.11 Save as set out above, BDA only uses the personal data or information 

collected from Patients in the manner set out in the section relating to “Registration 

Process” below. BDA may also use such information in an aggregated or non-
personally identifiable form for research, statistical analysis and business 

intelligence purposes, and may sell or otherwise transfer such research, statistical 

or intelligence data in an aggregated or non-personally identifiable forms to third 

parties and affiliates. If BDA wishes to use any Patients’ personal data for a new 

purpose, it will seek such Patients’ permission before doing so.</p><br/>
<p>8.12 To the extent necessary to provide Patients with the services on the Website, 

BDA may provide their Personal Information to third party contractors who 

work on behalf of or with BDA to provide Patients with such services, to help 

BDA communicate with Patients or to maintain the Website. Generally these 

contractors do not have any independent right to share this information, however 

certain contractors who provide services on the Website, including the providers 

of online communications services, will have rights to use and disclose the 

Personal Information collected in connection with the provision of these services in 

accordance with their own privacy policies.</p><br\>
<span>9. Casual Visitors Note:</span>
<p>9.1 No sensitive personal data or information is automatically collected by BDA

from any casual visitors of this website, who are merely perusing the site.</p><br/>
<p>9.2 Nevertheless, certain provisions of this privacy policy are applicable to even 

such casual visitors, and such casual visitors are also required to read and 

understand the privacy statements set out herein, failing which they are required to 

leave this website immediately.</p><br/>
<p>9.3 <strong>If you, as a casual visitor, have inadvertently browsed any other pages 

of this Website prior to reading the privacy statements set out herein</strong>, and 

you do not agree with the manner in which such information is obtained, stored or 

used, merely quitting this browser application should ordinarily clear all temporary 

cookies installed by BDA. All visitors, however, encouraged to use the “clear 

cookies” functionality of their browsers to ensure such clearing / deletion, as BDA 

cannot guarantee, predict or provide for the behavior of the equipment of all the 

visitors of the Website.</p><br/>
<p>9.4 You are not a casual visitor if you have willingly submitted any personal 

data or information to BDA through any means, including email, post or through the 

registration process on the Website. All such visitors will be deemed to be, and will 

be treated as, End Users for the purposes of this privacy policy, and in which case, 

all the statements in this privacy policy apply to such persons.</p><br/>
<span>10. Registration Process</span>
<p>10.1 As part of the registration process, BDA collects the following personal 

information from Users:</p><br/>

<p>i. Name;</p>

<p>ii. User ID;</p>

<p>iii. Email address;</p>

<p>iv. Address (including country and ZIP/postal code);</p>

<p>v. Gender;</p>

<p>vi. Age;</p>

<p>vii. Phone number;</p>

<p>viii. Password chosen by the User;</p>

<p>ix. Valid financial account information; and</p>

<p>x. Other details as the End User may volunteer.</p><br/>
<p>10.2 All the information listed in S. 10.1 of this privacy policy (“User 

Information”) is maintained by BDA in electronic form on its equipment, and 

on the equipment of its employees. End User Information may also be converted 

to physical form from time to time. Regardless of the manner of storage, BDA 

will keep all End User Information confidential, and will only disclose End User 

Information in the following manner:</p><br/>
<p>10.3 BDA makes all User Information accessible to its employees only on a need-to-
know basis, and binds all such employees to strict confidentiality obligations.</p><br/>
<p>10.4 Part of the functionality of the Software is assisting the doctors to maintain

and organise such information. BDA may, therefore, retain and submit all such 

records to the appropriate authorities, or to doctors who request access to such 

information.</p><br/>
<p>10.5 Part of the functionality of the Software is assisting the patients to access 

information relating to them. BDA may, therefore, retain and submit all such 

records to the relevant patients, or to their doctors.</p><br/>
<p>10.6 Notwithstanding the above, BDA shall not be responsible for any breach 

of security or for any actions of any third parties that receive Users’ personal 

data or events that are beyond the reasonable control of BDA including, acts of 

government, computer hacking, unauthorised access to computer data and storage 

device, computer crashes, breach of security and encryption, etc.</p><br/>

<span>11. Change to privacy policy</span>
<p>11.1 The Users acknowledge that this privacy policy is part of the terms of use 

and unconditionally agree that becoming a User of the Website and its Services 

signifies their assent to this privacy policy. User’s visit and any dispute over privacy 

is subject to this policy and terms of use. BDA may update this privacy policy at 

any time, with or without advance notice. In the event there are significant changes 

in the way BDA treats User’s personally identifiable information, BDA will display 

a notice on the Website or send Users an email, as provided for above. Unless 

stated otherwise, BDA’s current privacy policy applies to all information that BDA 

has about Users and their account. Notwithstanding the above, BDA shall not be 

required to notify the Users of any changes made to the privacy policy.</p><br/>
<p style="margin-bottom:15px;">11.2 If a User uses the Service after notice of changes have been sent to such User 

or published on the Website, such User hereby provides his/her/its consent to the 

changed practices.</p>






                </div>
</div><!--container cf End-->

</div><!--content End-->
<div id="footer">
	<?php $this->load->view('common/footer'); ?>
</div>  <?php $this->load->view('common/bottom'); ?>
</body>
</html>
